-- ----------------------------
-- 生产报工记录表
-- ----------------------------
drop table if exists pro_feedback;
create table pro_feedback (
  record_id                      bigint(20)      not null auto_increment    comment '记录ID',
  feedback_type                  varchar(64)     not null                   comment '报工类型',
  feedback_code                  varchar(64)                                comment '报工单编号',
  workstation_id                 bigint(20)      not null                   comment '工作站ID',
  workstation_code               varchar(64)                                comment '工作站编号',
  workstation_name               varchar(255)                               comment '工作站名称',
  workorder_id                   bigint(20)      not null                   comment '生产工单ID',
  workorder_code                 varchar(64)                                comment '生产工单编号',
  workorder_name                 varchar(255)                               comment '生产工单名称',
  route_id                       bigint(20)      not null                   comment '工艺流程ID',
  route_code                     varchar(64)                                comment '工艺流程编号',
  process_id                     bigint(20)      not null                   comment '工序ID',
  process_code                   varchar(64)                                comment '工序编码',
  process_name                   varchar(255)                               comment '工序名称',
  task_id                        bigint(20)                                 comment '生产任务ID',
  task_code                      varchar(64)                                comment '生产任务编号',
  item_id                        bigint(20)      not null                   comment '产品物料ID',
  item_code                      varchar(64)     not null                   comment '产品物料编码',
  item_name                      varchar(255)    not null                   comment '产品物料名称',
  unit_of_measure                varchar(64)                                comment '单位',
  unit_name                      varchar(64)                                comment '单位名称',
  specification                  varchar(500)                               comment '规格型号',
  expire_date                    datetime                                   comment '过期日期',
  lot_number                     varchar(128)                               comment '生产批号',
  quantity                       decimal(14,2)                              comment '排产数量',
  quantity_feedback              decimal(14,2)                              comment '本次报工数量',
  quantity_qualified             decimal(14,2)                              comment '合格品数量',
  quantity_unquanlified          decimal(14,2)                              comment '不良品数量',
  quantity_uncheck               decimal(14,2)                              comment '待检测数量',
  quantity_labor_scrap           decimal(14,2)                              comment '人工报废数量',
  quantity_material_scrap        decimal(14,2)                              comment '料废数量',
  quantity_other_scrap           decimal(14,2)                              comment '其他报废数量',
  user_name                      varchar(64)                                comment '报工用户名',
  nick_name                      varchar(64)                                comment '昵称',
  feedback_channel               varchar(64)                                comment '报工途径',
  feedback_time                  datetime                                   comment '报工时间',
  record_user                    varchar(64)                                comment '记录人',
  record_nick                    varchar(64)                                comment '记录人名称',
  status                         varchar(64)     default 'PREPARE'          comment '状态',
  remark                         varchar(500)    default ''                 comment '备注',
  attr1                          varchar(64)     default null               comment '预留字段1',
  attr2                          varchar(255)    default null               comment '预留字段2',
  attr3                          bigint(20)      default null               comment '预留字段3',
  attr4                          bigint(20)      default null               comment '预留字段4',
  create_by                      varchar(64)     default ''                 comment '创建者',
  create_time                    datetime                                   comment '创建时间',
  update_by                      varchar(64)     default ''                 comment '更新者',
  update_time                    datetime                                   comment '更新时间',
  primary key (record_id)
) engine=innodb auto_increment=1 comment = '生产报工记录表';
